### ISSUE TITLE
DICOM file

### ISSUE THREAD

**Issue by Gweiqi** [paulmtree/Lung-Segmentation-Project#3]
Dear paulmtree
This is an outstanding work. I am trying to simulate aerosol deposition in human lungs on a computer Your work are very helpful to my current research.Whether this program can be used to segment the lung airway from. Does the input file have to be in DICOM format?My file is in the NIFTY format. I use the software XMedCon to convert the NIFTY format to DICOM, but such error message appears:
"InvalidDicomError: File is missing DICOM File Meta Information header or the 'DICM' prefix is missing from the header. Use force=True to force reading."
Sincerely, yours

**Comment by paulmtree** [comment]
Hello and thank you for the kind words! The files don't need to be in DICOM format, as the preprocessing, including pixel rescaling and organizing of slices, is done with numpy. The load_scan method pulls the slice data from the DICOM files and converts to a series of numpy arrays, so you'll have to find the equivalent function for NIFTY format for pulling each slice. You are getting the InvalidDicomError because the file you are trying to read is not a DICOM file, so it won't be able to read it unless you try force=True in the read_file function on line 26. 

This should help. https://stackoverflow.com/questions/44422248/how-to-convert-nifti-file-to-numpy-array 

Once you load the data as a numpy array, you replace the load_scan function but with a few extra modifiers. You probably need to set the 'SliceThickness' attribute to whatever your nifti's slice thickness is along with 'PixelSpacing' since these attributes are referenced later in the script. However this doesn't seem super necessary in my opinion. From what I can tell this step is only useful for clinical people as the slice thickness doesn't seem to be used besides printing it for the user. If you don't want to go through the hassle, you can just omit these print statements where they are used and not define them in the first place.  

Let me know if you have additional questions!

Paul

**Comment by Gweiqi** [comment]
Dear paul
Thank you very much for your reply.According to your suggestion, I have modified lines 217-222 in DICOM processing.py. Here is the modified code:
_patient = nib.load(data_path).get_data
imgs =np.array(patient)
np.save(output_path + "fullimages_%d.npy" % (id), imgs)
file_used=output_path+"fullimages_%d.npy" % id
imgs_to_process = np.load(file_used,allow_pickle=True, fix_imports=True).astype(np.float64)_

But the following error message appeared:
  _File "E:\lung\Lung-Segmentation-Project-main\DICOM Processing.py", line 222, in <module>
    imgs_to_process = np.load(file_used,allow_pickle=True, fix_imports=True).astype(np.float64)
TypeError: float() argument must be a string or a number, not 'method'_
I have no way to find out the cause of this error, whether it is because I modified the modified code has an error.
Sincerely, yours
GuoWeiqi

**Comment by paulmtree** [comment]
The cause of the error is explained in the error message I believe. Whenever you use a new python function, make sure to check examples of how it is used. In this instance, the TypeError is given because you are giving the .astype() method a function, which is np.float64, instead of a string, 'float64'. 

Here is documentation on how to use .astype(): https://www.w3resource.com/pandas/series/series-astype.php.
